export { default as Bennefit } from './Benefit'
export { default as Location } from './Location'
export { default as About } from './About'
export { default as CartItem } from './CartItem'
export { default as CardItem } from './CardItem'export { default as WishList } from './WishList'
export{default as Button} from './Button'
export { default as Search } from './Search'
