export { default as Bennefit } from './Benefit'
export { default as Banner } from './Banner'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Location } from './Location'
export { default as About } from './About'